import turtle


scn = turtle.Screen()
geras = turtle.Turtle()
geras2 = turtle.Turtle()
flawer = turtle.Turtle()
haws = turtle.Turtle()
sky = turtle.Turtle()
sky2 = turtle.Turtle()
haws = turtle.Turtle()
roof = turtle.Turtle()
dor = turtle.Turtle()
sun = turtle.Turtle()


geras.speed(.5)
geras2.speed(.5)
flawer.speed(.5)
haws.speed(.5)
sky.speed(.5)
haws.speed(.5)
roof.speed(.5)
sky.speed(.5)
sky2.speed(.5)
sun.speed(.5)


def gera():
    geras.color("green")
    geras.begin_fill()
    geras.forward(1500)
    geras.right(90)
    geras.forward(1500)
    geras.right(90)
    geras.forward(1500)
    geras.end_fill()
    geras2.color("green")
    geras2.begin_fill()
    geras2.right(180)
    geras2.forward(1500)
    geras2.right(-90)
    geras2.forward(1500)
    geras2.right(-90)
    geras2.forward(1500)
    geras2.end_fill()
    geras2.goto(0, 0)
    geras.goto(0, 0)

def skys():
    sky.color("Turquoise")
    sky.begin_fill()
    sky.forward(1500)
    sky.right(-90)
    sky.forward(1500)
    sky.right(-90)
    sky.forward(1500)
    sky.end_fill()
    sky2.color("Turquoise")
    sky2.begin_fill()
    sky2.right(180)
    sky2.forward(1500)
    sky2.right(90)
    sky2.forward(1500)
    sky2.right(90)
    sky2.forward(1500)
    sky2.end_fill()
    sky2.goto(0, 0)
    sky.goto(0, 0)

def flawers():
    flawer.color("Goldenrod")
    flawer.pensize(7)
    flawer.right(-90)
    flawer.forward(60)
    flawer.right(90)
    flawer.pensize(1)
    flawer.color("Chartreuse")
    for i in range(15):
        flawer.begin_fill()
        for i in range(4):
            flawer.forward(20)
            flawer.right(-90)
        flawer.right(24)
        flawer.end_fill()
    flawer.color("Indian Red")
    flawer.right(90)
    flawer.forward(20)
    flawer.right(270)
    flawer.begin_fill()
    flawer.circle(20)
    flawer.end_fill()
    flawer.right(-90)
    flawer.forward(20)


def Haws():
    haws.begin_fill()
    haws.color("Medium Violet Red")
    haws.forward(230)
    haws.right(-90)
    haws.forward(110)
    haws.right(-90)
    haws.forward(230)
    haws.end_fill()
    haws.begin_fill()
    haws.color("Red")
    haws.forward(100)
    haws.right(-90)
    haws.forward(110)
    haws.right(-90)
    haws.forward(100)
    haws.end_fill()


def roofs():
    roof.begin_fill()
    roof.color("Medium Violet Red")
    roof.right(-90)
    roof.forward(110)
    roof.right(-45)
    roof.forward(71)
    roof.right(-90)
    roof.forward(72)
    roof.right(-135)
    roof.forward(110)
    roof.end_fill()
    roof.color("Red")
    roof.penup()
    roof.goto(-50, 160)
    roof.pendown()
    roof.begin_fill()
    roof.forward(230)
    roof.right(45)
    roof.forward(72)
    roof.right(135)
    roof.forward(230)
    roof.right(45)
    roof.forward(71)
    roof.end_fill()
    roof.penup()
    roof.goto(0, 0)

def doers():
    dor.begin_fill()
    dor.color("brown")
    dor.penup()
    dor.forward(30)
    dor.right(-90)
    dor.forward(70)
    dor.right(90)
    dor.forward(45)
    dor.right(90)
    dor.forward(70)
    dor.end_fill()
    dor.backward(25)
    dor.right(-180)
    dor.color("white")
    dor.begin_fill()
    dor.circle(4)
    dor.end_fill()
    dor.forward(35)
    dor.right(-90)
    dor.forward(10)
    dor.pendown()
    dor.pensize(2)
    dor.begin_fill()
    dor.forward(25)
    dor.right(-90)
    dor.forward(25)
    dor.right(-90)
    dor.forward(25)
    dor.right(-90)
    dor.forward(25)
    dor.color("Light Slate Gray")
    dor.end_fill()
    dor.color("white")
    dor.right(-90)
    dor.forward(12.5)
    dor.right(-90)
    dor.forward(25)
    dor.right(-90)
    dor.forward(12.5)
    dor.right(-90)
    dor.forward(12.5)
    dor.right(-90)
    dor.forward(25)
    dor.penup()
    dor.goto(0, 0)

def sunray():
    sun.color("yellow")
    sun.penup()
    sun.goto(-400, 200)
    sun.pendown()
    sun.begin_fill()
    sun.circle(150)
    sun.end_fill()
    sun.right(-90)
    sun.forward(150)
    sun.pensize(8)
    for i in range(36):
        sun.right(10)
        sun.forward(200)
        sun.backward(200)



skys()
sunray()
Haws()
roofs()
gera()
flawer.goto(-90, -90)
flawers()
flawer.penup()
flawer.goto(-190, -90)
flawer.right(90)
flawer.pendown()
flawers()
flawer.penup()
flawer.goto(190, -90)
flawer.right(90)
flawer.pendown()
flawers()
flawer.penup()
flawer.goto(-10, -90)
flawer.right(90)
flawer.pendown()
flawers()
flawer.penup()
flawer.goto(90, -90)
flawer.right(90)
flawer.pendown()
flawers()
flawer.penup()
flawer.goto(90, -200)
flawer.right(90)
flawer.pendown()
flawers()
flawer.penup()
flawer.goto(160, -200)
flawer.right(90)
flawer.pendown()
flawers()





doers()


turtle.exitonclick()


